server:
  port: 8090

openweathermap:
  api:
    key: e156e27a3826eebeaff26f7eecba4a1d

nasa:
  api:
    key: QtXaKbPv2H4dPIHuhQzK4CaR4tJMNa4xrbdk2igY
jwt_secret: ${my_secret}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/jwt_security
    username: postgres #${JDBC_USER}
    password: defaultp@ssword1 #${JDBC_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect