server:
  port: 8080

openweathermap:
  api:
    key: e156e27a3826eebeaff26f7eecba4a1d

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=weatherapp
    username: postgres
    password: admin